"use client";
import { Banknote, CalendarClock, Dices, Skull, Trophy } from "lucide-react";
import { useState } from "react";
import { createPenalty } from "./actions";
import { PENALTY_CATEGORIES, PENALTY_PRESETS } from "@/lib/penalties";

type Member={id:string;username:string;avatarUrl:string|null};
export default function PenaltyForm({members,enabledCategories}:{members:Member[];enabledCategories:string[]}){
 const [title,setTitle]=useState(""); const [category,setCategory]=useState("challenge"); const [amount,setAmount]=useState(""); const [spin,setSpin]=useState(false);
 function choosePreset(p:typeof PENALTY_PRESETS[number]){setTitle(p.title);setCategory(p.category);setAmount("amount" in p&&p.amount?p.amount:"")}
 function wheel(){setSpin(true); let ticks=0; const timer=setInterval(()=>{choosePreset(PENALTY_PRESETS[Math.floor(Math.random()*PENALTY_PRESETS.length)]);ticks++;if(ticks>=12){clearInterval(timer);setSpin(false)}},70)}
 return <form action={createPenalty} className="space-y-7 px-5 py-6">
  <section><div className="mb-3 flex items-center gap-2"><Skull size={18} className="text-red-400"/><label className="text-sm font-black uppercase tracking-wide">Chi ha perso?</label></div><div className="grid grid-cols-2 gap-3">{members.map(m=><label key={m.id} className="cursor-pointer"><input type="radio" name="assignedTo" value={m.id} required className="peer sr-only"/><div className="rounded-2xl border border-white/10 bg-zinc-900 p-4 peer-checked:border-lime-400 peer-checked:bg-lime-400/10"><div className="mb-3 h-11 w-11 overflow-hidden rounded-full bg-zinc-800">{m.avatarUrl?<img src={m.avatarUrl} alt={m.username} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center font-black">{m.username[0]?.toUpperCase()}</div>}</div><p className="font-black">{m.username}</p></div></label>)}</div></section>
  <section className="rounded-3xl border border-fuchsia-400/10 bg-fuchsia-400/5 p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-black">🎡 Ruota della Sfiga</p><p className="text-xs text-zinc-500">Non sapete cosa assegnare? Decide PayUp.</p></div><button type="button" onClick={wheel} disabled={spin} className="flex h-11 items-center gap-2 rounded-2xl bg-fuchsia-400 px-4 text-sm font-black text-black"><Dices size={18} className={spin?"animate-spin":""}/>{spin?"...":"GIRA"}</button></div></section>
  <section><div className="mb-3 flex items-center gap-2"><Trophy size={18} className="text-lime-400"/><label className="text-sm font-black uppercase">Cosa deve fare?</label></div><input name="title" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={200} placeholder="Es. Offrire una pizza al gruppo" className="h-14 w-full rounded-2xl border border-white/10 bg-zinc-900 px-4 font-semibold outline-none focus:border-lime-400"/><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{PENALTY_PRESETS.slice(0,6).map(p=><button key={p.title} type="button" onClick={()=>choosePreset(p)} className="shrink-0 rounded-full bg-zinc-900 px-3 py-2 text-xs font-bold text-zinc-400">{p.title}</button>)}</div></section>
  <section><label className="mb-3 block text-sm font-black uppercase">Categoria</label><div className="grid grid-cols-2 gap-2">{PENALTY_CATEGORIES.filter(c=>enabledCategories.includes(c.value)).map(c=><label key={c.value}><input type="radio" name="category" value={c.value} checked={category===c.value} onChange={()=>setCategory(c.value)} className="peer sr-only"/><div className="cursor-pointer rounded-2xl border border-white/10 bg-zinc-900 p-3 text-sm font-black peer-checked:border-lime-400 peer-checked:bg-lime-400/10">{c.label}</div></label>)}</div></section>
  <section><div className="mb-3 flex items-center gap-2"><Banknote size={18} className="text-emerald-400"/><label className="text-sm font-black uppercase">Importo</label><span className="text-xs text-zinc-600">opzionale</span></div><div className="relative"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-xl font-black text-zinc-500">€</span><input name="amount" value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0" step="0.01" placeholder="0,00" className="h-14 w-full rounded-2xl border border-white/10 bg-zinc-900 pl-11 pr-4 text-lg font-black outline-none focus:border-lime-400"/></div></section>
  <section><div className="mb-3 flex items-center gap-2"><CalendarClock size={18} className="text-amber-300"/><label className="text-sm font-black uppercase">Scadenza</label><span className="text-xs text-zinc-600">opzionale</span></div><input name="dueAt" type="datetime-local" className="h-14 w-full rounded-2xl border border-white/10 bg-zinc-900 px-4 outline-none focus:border-amber-300"/></section>
  <section><label className="mb-3 block text-sm font-black uppercase">Note <span className="text-xs font-normal normal-case text-zinc-600">opzionale</span></label><textarea name="description" rows={4} placeholder="Aggiungi dettagli..." className="w-full resize-none rounded-2xl border border-white/10 bg-zinc-900 p-4 outline-none focus:border-lime-400"/></section>
  <button className="flex h-16 w-full items-center justify-center gap-2 rounded-3xl bg-lime-400 text-lg font-black text-black"><Skull size={22}/>ASSEGNA PENITENZA</button>
 </form>
}
