import Link from "next/link";
import { and, desc, eq, sql } from "drizzle-orm";
import { BadgeCheck, Bell, CircleDollarSign, Clock3, Flame, Home, Plus, Skull, ThumbsDown, ThumbsUp, Trophy, User, UsersRound } from "lucide-react";
import { db } from "@/db";
import { groups, notifications, penalties, proofs, users, votes } from "@/db/schema";
import ProofMedia from "@/components/proof-media";
import { categoryLabel } from "@/lib/penalties";
import { requirePayupContext } from "@/lib/auth";
import { voteOnProof } from "./vote-actions";

export const dynamic = "force-dynamic";

export default async function Dashboard() {
  const { user, group } = await requirePayupContext();

  const openPenalties = await db.select({ id: penalties.id, title: penalties.title, amountCents: penalties.amountCents, category: penalties.category, dueAt: penalties.dueAt, createdAt: penalties.createdAt, username: users.username, avatarUrl: users.avatarUrl })
    .from(penalties).innerJoin(users, eq(penalties.assignedTo, users.id))
    .where(and(eq(penalties.groupId, group.groupId), eq(penalties.status, "pending"))).orderBy(desc(penalties.createdAt));

  const verificationPosts = await db.select({ proofId: proofs.id, penaltyId: penalties.id, penaltyTitle: penalties.title, mediaUrl: proofs.mediaUrl, mediaType: proofs.mediaType, caption: proofs.caption, uploadedBy: proofs.uploadedBy, username: users.username, avatarUrl: users.avatarUrl, requiredVotes: groups.verificationVotes, confirmations: sql<number>`count(case when ${votes.confirmed} = true then 1 end)`, fakeVotes: sql<number>`count(case when ${votes.confirmed} = false then 1 end)` })
    .from(proofs).innerJoin(penalties, eq(proofs.penaltyId, penalties.id)).innerJoin(groups, eq(penalties.groupId, groups.id)).innerJoin(users, eq(proofs.uploadedBy, users.id)).leftJoin(votes, eq(votes.proofId, proofs.id))
    .where(and(eq(penalties.groupId, group.groupId), eq(penalties.status, "verifying"))).groupBy(proofs.id, penalties.id, users.username, users.avatarUrl, groups.verificationVotes).orderBy(desc(proofs.createdAt));

  const completedPenalties = await db.select({ id: penalties.id, title: penalties.title, username: users.username, avatarUrl: users.avatarUrl }).from(penalties).innerJoin(users, eq(penalties.assignedTo, users.id)).where(and(eq(penalties.groupId, group.groupId), eq(penalties.status, "completed"))).orderBy(desc(penalties.completedAt)).limit(3);
  const currentUserVotes = await db.select({ proofId: votes.proofId, confirmed: votes.confirmed }).from(votes).where(eq(votes.userId, user.id));
  const [{ unread }] = await db.select({ unread: sql<number>`count(*)` }).from(notifications).where(and(eq(notifications.userId,user.id),eq(notifications.isRead,false)));

  return <main className="min-h-screen bg-zinc-950 text-white"><div className="mx-auto min-h-screen max-w-md border-x border-white/5 pb-28">
    <header className="sticky safe-sticky-top z-20 border-b border-white/5 bg-zinc-950/95 px-5 pb-4 pt-5 backdrop-blur"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.3em] text-lime-400">PayUp</p><h1 className="mt-1 text-2xl font-black">Ciao {user.username} 👋</h1><Link href="/group" className="mt-2 inline-flex items-center gap-1.5 text-xs font-bold text-zinc-500"><UsersRound size={14}/>{group.name} ▾</Link></div><div className="flex items-center gap-2"><Link href="/notifications" className="relative flex h-11 w-11 items-center justify-center rounded-full bg-zinc-900"><Bell size={19}/>{Number(unread)>0&&<span className="absolute -right-1 -top-1 flex min-h-5 min-w-5 items-center justify-center rounded-full bg-red-500 px-1 text-[10px] font-black">{Number(unread)>9?"9+":Number(unread)}</span>}</Link><Link href="/profile" className="h-11 w-11 overflow-hidden rounded-full bg-zinc-900">{user.avatarUrl?<img src={user.avatarUrl} alt={user.username} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center"><User size={20}/></div>}</Link></div></div>
      <div className="mt-5 grid grid-cols-3 gap-2"><Stat icon={<Skull size={16}/>} value={openPenalties.length} label="Debiti"/><Stat icon={<Flame size={16}/>} value={verificationPosts.length} label="Da verificare"/><Stat icon={<Trophy size={16}/>} value={completedPenalties.length} label="Completate"/></div>
    </header>

    <div className="space-y-8 px-5 py-6">
      <section><div className="mb-4"><p className="text-sm font-black uppercase tracking-wide">🔥 Da verificare</p><p className="mt-1 text-xs text-zinc-500">Dai il tuo verdetto</p></div>{verificationPosts.length===0 ? <Empty text="Nessuna prova da verificare" emoji="✅"/> : <div className="space-y-4">{verificationPosts.map((post)=>{const conf=Number(post.confirmations); const fake=Number(post.fakeVotes); const req=post.requiredVotes||3; const myVote=currentUserVotes.find(v=>v.proofId===post.proofId); const own=user.id===post.uploadedBy; return <article key={post.proofId} className="overflow-hidden rounded-3xl border border-white/10 bg-zinc-900"><div className="p-4"><div className="flex items-center gap-3"><Avatar username={post.username} avatarUrl={post.avatarUrl}/><div className="flex-1"><p className="font-black">{post.username}</p><p className="text-sm text-zinc-400">dice di averla fatta</p></div><Clock3 size={18} className="text-zinc-600"/></div><p className="mt-4 rounded-2xl bg-zinc-800/70 p-4 font-semibold">💀 {post.penaltyTitle}</p></div><ProofMedia src={post.mediaUrl} type={post.mediaType} alt="Prova" proofId={post.proofId}/><div className="p-4">{post.caption&&<p className="mb-4 text-sm text-zinc-300">“{post.caption}”</p>}<div className="mb-3 flex justify-between text-sm font-black"><span>{conf}/{req} conferme</span><span className="text-red-400">{fake} fake</span></div><div className="h-2 overflow-hidden rounded-full bg-zinc-800"><div className="h-full rounded-full bg-lime-400" style={{width:`${Math.min(conf/req*100,100)}%`}}/></div>{own?<p className="mt-4 rounded-2xl bg-zinc-800 p-3 text-center text-sm font-bold text-zinc-400">È la tua prova: niente autovoto 👀</p>:myVote?<p className={`mt-4 rounded-2xl p-3 text-center text-sm font-black ${myVote.confirmed?"bg-lime-400/10 text-lime-300":"bg-red-500/10 text-red-400"}`}>{myVote.confirmed?"✅ Hai confermato":"🤡 Hai votato FAKE"}</p>:<div className="mt-4 grid grid-cols-2 gap-3"><form action={voteOnProof}><input type="hidden" name="proofId" value={post.proofId}/><input type="hidden" name="vote" value="confirm"/><button className="flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-lime-400 font-black text-black"><ThumbsUp size={18}/>CONFERMO</button></form><form action={voteOnProof}><input type="hidden" name="proofId" value={post.proofId}/><input type="hidden" name="vote" value="fake"/><button className="flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-red-500/10 font-black text-red-400"><ThumbsDown size={18}/>FAKE</button></form></div>}</div></article>})}</div>}</section>

      <section><div className="mb-4"><p className="text-sm font-black uppercase tracking-wide">💀 Debiti aperti</p><p className="mt-1 text-xs text-zinc-500">Chi deve ancora pagare</p></div>{openPenalties.length===0?<Empty text="Nessun debito aperto" emoji="😇"/>:<div className="space-y-3">{openPenalties.map(item=><Link key={item.id} href={`/penalties/${item.id}`} className="flex items-center gap-4 rounded-2xl bg-zinc-900 p-4"><Avatar username={item.username} avatarUrl={item.avatarUrl}/><div className="min-w-0 flex-1"><p className="font-black">{item.username}</p><p className="text-xs font-bold text-zinc-500">{categoryLabel(item.category)}</p><p className="truncate text-sm text-zinc-300">{item.title}</p>{item.dueAt&&<p className={`mt-1 text-xs font-bold ${item.dueAt < new Date()?"text-red-400":"text-amber-300"}`}>⏰ {new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(item.dueAt)}</p>}{item.amountCents!==null&&<p className="mt-1 text-sm font-black text-emerald-400">{formatMoney(item.amountCents)}</p>}</div><span className="rounded-full bg-red-500/10 px-3 py-1 text-[10px] font-black text-red-400">DA FARE</span></Link>)}</div>}</section>

      {completedPenalties.length>0&&<section><p className="mb-4 text-sm font-black uppercase">✅ Fatto per davvero</p><div className="space-y-3">{completedPenalties.map(item=><Link key={item.id} href={`/penalties/${item.id}`} className="flex items-center gap-3 rounded-2xl border border-lime-400/10 bg-lime-400/5 p-4"><Avatar username={item.username} avatarUrl={item.avatarUrl}/><div><p className="font-black">{item.username}</p><p className="text-sm text-zinc-400">{item.title}</p></div></Link>)}</div></section>}
      <Link href="/add" className="flex h-16 w-full items-center justify-center gap-3 rounded-3xl bg-lime-400 text-lg font-black text-black"><Plus size={24}/>NUOVA SCONFITTA</Link>
    </div>
    <BottomNav/>
  </div></main>;
}

function Avatar({username,avatarUrl}:{username:string;avatarUrl:string|null}){return <div className="h-11 w-11 shrink-0 overflow-hidden rounded-full bg-lime-400 text-black">{avatarUrl?<img src={avatarUrl} alt={username} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center font-black">{username[0]?.toUpperCase()}</div>}</div>}
function Stat({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <div className="rounded-2xl bg-zinc-900 p-3"><div className="flex items-center gap-2 text-lime-400">{icon}<span className="text-lg font-black text-white">{value}</span></div><p className="mt-1 text-[11px] font-bold text-zinc-500">{label}</p></div>}
function Empty({text,emoji}:{text:string;emoji:string}){return <div className="rounded-3xl border border-dashed border-white/10 bg-zinc-900/40 p-8 text-center"><p className="text-4xl">{emoji}</p><p className="mt-3 font-black">{text}</p></div>}
function formatMoney(c:number){return new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}).format(c/100)}
function BottomNav(){return <nav className="fixed bottom-0 left-1/2 z-30 flex w-full max-w-md -translate-x-1/2 items-center justify-around border-t border-white/10 bg-zinc-950/95 px-2 pb-5 pt-3"><Link href="/" className="flex min-w-14 flex-col items-center gap-1 text-[10px] font-bold text-lime-400"><Home size={20}/>Home</Link><Link href="/feed" className="flex min-w-14 flex-col items-center gap-1 text-[10px] font-bold text-zinc-500"><Flame size={20}/>The Wall</Link><Link href="/add" className="-mt-8 flex h-14 w-14 items-center justify-center rounded-full bg-lime-400 text-black"><Plus size={26}/></Link><Link href="/ranking" className="flex min-w-14 flex-col items-center gap-1 text-[10px] font-bold text-zinc-500"><Trophy size={20}/>Ranking</Link><Link href="/profile" className="flex min-w-14 flex-col items-center gap-1 text-[10px] font-bold text-zinc-500"><User size={20}/>Profilo</Link></nav>}
