import Link from "next/link";
import { ArrowLeft, BellRing, Flag, ShieldCheck } from "lucide-react";
import { requirePayupContext } from "@/lib/auth";
import { startNewSeasonAction, updateGroupSettingsAction } from "../actions";
export default async function SettingsPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){const {group}=await requirePayupContext();const p=await searchParams;if(group.role!=='admin')return <main className="min-h-screen bg-zinc-950 p-6 text-white"><p>Solo gli admin possono aprire questa pagina.</p></main>;const enabled=(group.enabledCategories||'').split(',');return <main className="min-h-screen bg-zinc-950 text-white"><div className="mx-auto max-w-md px-5 py-5"><div className="flex items-center gap-3"><Link href="/group" className="flex h-11 w-11 items-center justify-center rounded-full bg-zinc-900"><ArrowLeft size={20}/></Link><div><p className="text-xs font-black uppercase tracking-[.2em] text-lime-400">{group.name}</p><h1 className="text-xl font-black">Impostazioni gruppo</h1></div></div>{p.success&&<p className="mt-4 rounded-2xl bg-lime-400/10 p-3 text-sm font-bold text-lime-300">✓ {p.success}</p>}
<form action={updateGroupSettingsAction} className="mt-6 space-y-5"><input type="hidden" name="groupId" value={group.groupId}/><section className="rounded-3xl bg-zinc-900 p-5"><h2 className="flex items-center gap-2 font-black"><ShieldCheck size={18} className="text-lime-400"/>Verifica prove</h2><label className="mt-4 block text-xs font-bold uppercase text-zinc-500">Conferme necessarie</label><input type="number" min={1} max={10} name="verificationVotes" defaultValue={group.verificationVotes} className="mt-2 h-12 w-full rounded-2xl bg-zinc-950 px-4 font-black"/></section>
<section className="rounded-3xl bg-zinc-900 p-5"><h2 className="font-black">Categorie abilitate</h2><div className="mt-3 grid grid-cols-2 gap-2">{[['money','💸 Soldi'],['drink','🍺 Bere'],['food','🍕 Cibo'],['challenge','🤡 Challenge'],['other','🎲 Altro']].map(([v,l])=><label key={v} className="flex items-center gap-2 rounded-2xl bg-zinc-950 p-3 text-sm font-bold"><input type="checkbox" name="categories" value={v} defaultChecked={enabled.includes(v)}/>{l}</label>)}</div></section>
<section className="rounded-3xl bg-zinc-900 p-5"><h2 className="flex items-center gap-2 font-black"><BellRing size={18} className="text-amber-300"/>The Wall</h2><label className="mt-4 flex items-center justify-between rounded-2xl bg-zinc-950 p-4"><span><b>The Wall abilitato</b><small className="block text-zinc-500">Permette prove pubbliche</small></span><input type="checkbox" name="wallEnabled" defaultChecked={group.wallEnabled}/></label><label className="mt-3 flex items-center justify-between rounded-2xl bg-zinc-950 p-4"><span><b>Pubblica di default</b><small className="block text-zinc-500">L'utente può sempre cambiarlo</small></span><input type="checkbox" name="defaultProofPublic" defaultChecked={group.defaultProofPublic}/></label></section><button className="h-14 w-full rounded-2xl bg-lime-400 font-black text-black">SALVA IMPOSTAZIONI</button></form>
<section className="mt-5 rounded-3xl border border-amber-300/10 bg-zinc-900 p-5"><h2 className="flex items-center gap-2 font-black"><Flag size={18} className="text-amber-300"/>Stagione</h2><p className="mt-2 text-sm text-zinc-500">Iniziata il {new Intl.DateTimeFormat('it-IT',{dateStyle:'medium'}).format(group.seasonStartedAt)}</p><form action={startNewSeasonAction} className="mt-4"><input type="hidden" name="groupId" value={group.groupId}/><button className="h-11 w-full rounded-2xl bg-amber-300/10 font-black text-amber-300">🏁 INIZIA NUOVA STAGIONE</button></form></section></div></main>}
