"use client";
import { upload } from "@vercel/blob/client";
import { Camera, LockKeyhole, Loader2 } from "lucide-react";
import { useState } from "react";
import { updateAvatarAction, updateManagedAvatarAction } from "./actions";

type AvatarOption={id:string;name:string;imageUrl:string;type:string;available:boolean;progress:number;required:number;seasonalStart:string|null;seasonalEnd:string|null;unlockType:string|null};
export default function AvatarUploader({ userId, username, avatarUrl, options }: { userId: string; username: string; avatarUrl: string | null; options:AvatarOption[] }) {
  const [preview, setPreview] = useState(avatarUrl);const [uploading,setUploading]=useState(false);const[error,setError]=useState("");
  async function handleFile(file?:File){if(!file)return;if(!file.type.startsWith("image/"))return setError("Scegli una foto valida.");if(file.size>5*1024*1024)return setError("La foto deve pesare massimo 5 MB.");setUploading(true);setError("");setPreview(URL.createObjectURL(file));try{const blob=await upload(`avatars/${userId}/${file.name}`,file,{access:"public",handleUploadUrl:"/api/avatar-upload"});await updateAvatarAction(blob.url)}catch(err){console.error(err);setError("Non sono riuscito a caricare la foto.");setUploading(false)}}
  const base=options.filter(a=>a.type==='base');const seasonal=options.filter(a=>a.type==='seasonal');const unlockable=options.filter(a=>a.type==='unlockable');
  return <div><div className="flex items-center gap-4"><div className="relative h-24 w-24 shrink-0 overflow-hidden rounded-full bg-lime-400 text-black ring-2 ring-lime-400/20">{preview?<img src={preview} alt={`Avatar di ${username}`} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center text-3xl font-black">{username[0]?.toUpperCase()}</div>}{uploading&&<div className="absolute inset-0 flex items-center justify-center bg-black/60 text-white"><Loader2 className="animate-spin"/></div>}</div><div className="min-w-0 flex-1"><p className="font-black">Il tuo avatar</p><p className="mt-1 text-xs leading-5 text-zinc-500">Scegli un teschio PayUp oppure usa una tua foto.</p><label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-2xl bg-zinc-800 px-4 py-2.5 text-sm font-black"><Camera size={17}/> CARICA FOTO<input type="file" accept="image/*" className="hidden" disabled={uploading} onChange={e=>handleFile(e.target.files?.[0])}/></label>{error&&<p className="mt-2 text-xs font-bold text-red-400">{error}</p>}</div></div><AvatarGrid title="Teschi base 💀" subtitle="Sempre disponibili" items={base} preview={preview} setPreview={setPreview}/>{seasonal.length>0&&<AvatarGrid title="Avatar stagionali 🎉" subtitle="Compaiono automaticamente durante le feste" items={seasonal} preview={preview} setPreview={setPreview}/>} {unlockable.length>0&&<AvatarGrid title="Da sbloccare 🔒" subtitle="Completa gli obiettivi per ottenerli" items={unlockable} preview={preview} setPreview={setPreview}/>}</div>
}
function AvatarGrid({title,subtitle,items,preview,setPreview}:{title:string;subtitle:string;items:AvatarOption[];preview:string|null;setPreview:(x:string)=>void}){return <div className="mt-5"><div><p className="font-black">{title}</p><p className="mt-1 text-xs text-zinc-500">{subtitle}</p></div><div className="mt-3 grid grid-cols-4 gap-2">{items.map(a=><form action={updateManagedAvatarAction} key={a.id}><input type="hidden" name="avatarId" value={a.id}/><button type="submit" disabled={!a.available} onClick={()=>a.available&&setPreview(a.imageUrl)} className={`relative w-full rounded-2xl border-2 p-1 transition active:scale-95 disabled:opacity-45 ${preview===a.imageUrl?'border-lime-400 bg-lime-400/10':'border-transparent bg-zinc-950'}`}><img src={a.imageUrl} alt={a.name} className="aspect-square w-full rounded-xl object-cover"/>{!a.available&&<span className="absolute right-1 top-1 flex h-6 w-6 items-center justify-center rounded-full bg-black/80"><LockKeyhole size={12}/></span>}<span className="mt-1 block truncate text-[8px] font-black text-zinc-500">{a.name}</span>{!a.available&&a.type==='unlockable'&&<span className="block text-[8px] font-black text-amber-300">{a.progress}/{a.required}</span>}</button></form>)}</div></div>}
