"use server";
import { and, eq, ne, sql } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { db } from "@/db";
import { avatars, userAvatarUnlocks, users } from "@/db/schema";
import { requirePayUpAdmin } from "@/lib/auth";

function back(type:"success"|"error",message:string):never{redirect(`/admin/avatars?${type}=${encodeURIComponent(message)}`)}
const validType=(x:string)=>["base","seasonal","unlockable"].includes(x);
const validUnlock=(x:string)=>["season_wins","trending_count","completed_penalties","spent_euros"].includes(x);
const md=(x:string)=>/^\d{2}-\d{2}$/.test(x);

export async function createAvatarAction(formData:FormData){await requirePayUpAdmin();const name=(formData.get("name")?.toString()??"").trim();const imageUrl=formData.get("imageUrl")?.toString()??"";const type=formData.get("type")?.toString()??"base";const slug=(formData.get("slug")?.toString()??name).trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80);if(!name||!imageUrl||!slug)back("error","Nome e immagine sono obbligatori.");if(!validType(type))back("error","Tipo avatar non valido.");const [exists]=await db.select({id:avatars.id}).from(avatars).where(eq(avatars.slug,slug)).limit(1);if(exists)back("error","Esiste già un avatar con questo slug.");const seasonalStart=(formData.get("seasonalStart")?.toString()??"").trim()||null;const seasonalEnd=(formData.get("seasonalEnd")?.toString()??"").trim()||null;if(type==="seasonal"&&(!seasonalStart||!seasonalEnd||!md(seasonalStart)||!md(seasonalEnd)))back("error","Per gli stagionali usa date MM-GG, es. 10-01.");const unlockType=(formData.get("unlockType")?.toString()??"").trim()||null;const unlockValue=Number(formData.get("unlockValue")||0)||null;if(type==="unlockable"&&(!unlockType||!validUnlock(unlockType)||!unlockValue))back("error","Imposta requisito e quantità per lo sblocco.");const [max]=await db.select({v:sql<number>`coalesce(max(${avatars.sortOrder}),0)`}).from(avatars);await db.insert(avatars).values({slug,name,imageUrl,type,seasonalStart:type==='seasonal'?seasonalStart:null,seasonalEnd:type==='seasonal'?seasonalEnd:null,keepAfterUnlock:formData.get("keepAfterUnlock")==="on",unlockType:type==='unlockable'?unlockType:null,unlockValue:type==='unlockable'?unlockValue:null,active:true,sortOrder:Number(max?.v??0)+10});revalidatePath('/admin/avatars');back('success','Avatar creato.')}

export async function updateAvatarAction(formData:FormData){await requirePayUpAdmin();const id=formData.get('id')?.toString()??'';const name=(formData.get('name')?.toString()??'').trim();const type=formData.get('type')?.toString()??'base';const seasonalStart=(formData.get('seasonalStart')?.toString()??'').trim()||null;const seasonalEnd=(formData.get('seasonalEnd')?.toString()??'').trim()||null;const unlockType=(formData.get('unlockType')?.toString()??'').trim()||null;const unlockValue=Number(formData.get('unlockValue')||0)||null;if(!id||!name||!validType(type))back('error','Dati avatar non validi.');if(type==='seasonal'&&(!seasonalStart||!seasonalEnd||!md(seasonalStart)||!md(seasonalEnd)))back('error','Date stagionali non valide. Usa MM-GG.');if(type==='unlockable'&&(!unlockType||!validUnlock(unlockType)||!unlockValue))back('error','Requisito sblocco non valido.');await db.update(avatars).set({name,type,seasonalStart:type==='seasonal'?seasonalStart:null,seasonalEnd:type==='seasonal'?seasonalEnd:null,keepAfterUnlock:formData.get('keepAfterUnlock')==='on',unlockType:type==='unlockable'?unlockType:null,unlockValue:type==='unlockable'?unlockValue:null,updatedAt:new Date()}).where(eq(avatars.id,id));revalidatePath('/admin/avatars');revalidatePath('/profile');revalidatePath('/register');back('success','Avatar aggiornato.')}

export async function toggleAvatarAction(formData:FormData){await requirePayUpAdmin();const id=formData.get('id')?.toString()??'';const active=formData.get('active')==='true';await db.update(avatars).set({active:!active,updatedAt:new Date()}).where(eq(avatars.id,id));revalidatePath('/admin/avatars');revalidatePath('/profile');revalidatePath('/register');}

export async function moveAvatarAction(formData:FormData){await requirePayUpAdmin();const id=formData.get('id')?.toString()??'';const direction=formData.get('direction')?.toString()==='up'?-1:1;const all=await db.select({id:avatars.id,sortOrder:avatars.sortOrder}).from(avatars).orderBy(avatars.sortOrder);const idx=all.findIndex(x=>x.id===id);const other=all[idx+direction];if(idx<0||!other)return;const current=all[idx];await db.update(avatars).set({sortOrder:other.sortOrder}).where(eq(avatars.id,current.id));await db.update(avatars).set({sortOrder:current.sortOrder}).where(eq(avatars.id,other.id));revalidatePath('/admin/avatars');}

export async function grantAvatarAction(formData:FormData){await requirePayUpAdmin();const avatarId=formData.get('avatarId')?.toString()??'';const username=(formData.get('username')?.toString()??'').trim();const [u]=await db.select({id:users.id}).from(users).where(sql`lower(${users.username})=${username.toLowerCase()}`).limit(1);if(!u)back('error','Utente non trovato.');await db.insert(userAvatarUnlocks).values({userId:u.id,avatarId,source:'admin'}).onConflictDoNothing();back('success',`Avatar sbloccato per @${username}.`)}
