"use client";
import { upload } from "@vercel/blob/client";
import { Loader2, Upload } from "lucide-react";
import { useState } from "react";
import { createAvatarAction } from "./actions";

export default function NewAvatarForm(){const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!file)return setError('Scegli prima un’immagine.');setBusy(true);setError('');try{const blob=await upload(`avatar-cms/${Date.now()}-${file.name}`,file,{access:'public',handleUploadUrl:'/api/admin-avatar-upload'});const fd=new FormData(e.currentTarget);fd.set('imageUrl',blob.url);await createAvatarAction(fd);}catch(err){console.error(err);setError('Upload fallito. Riprova.');setBusy(false)}}return <form onSubmit={submit} className="space-y-4 rounded-3xl border border-lime-400/15 bg-zinc-900 p-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-lime-300">Nuovo avatar</p><h2 className="mt-1 text-xl font-black">Carica e configura</h2></div><label className="block cursor-pointer rounded-2xl border-2 border-dashed border-white/10 bg-zinc-950 p-4 text-center">{preview?<img src={preview} alt="Anteprima" className="mx-auto aspect-square w-32 rounded-2xl object-cover"/>:<div className="py-6 text-zinc-500"><Upload className="mx-auto"/><p className="mt-2 text-sm font-bold">PNG / JPG / WEBP</p></div>}<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0]??null;setFile(f);setPreview(f?URL.createObjectURL(f):null)}}/></label><input name="name" required placeholder="Nome avatar" className="h-12 w-full rounded-xl bg-zinc-950 px-4 outline-none focus:ring-2 focus:ring-lime-400"/><input name="slug" placeholder="slug (facoltativo)" className="h-12 w-full rounded-xl bg-zinc-950 px-4 outline-none focus:ring-2 focus:ring-lime-400"/><TypeFields/>{error&&<p className="rounded-xl bg-red-500/10 p-3 text-sm font-bold text-red-300">{error}</p>}<button disabled={busy} className="flex h-13 w-full items-center justify-center gap-2 rounded-2xl bg-lime-400 px-4 py-3 font-black text-black disabled:opacity-50">{busy?<Loader2 className="animate-spin"/>:<Upload size={18}/>} CREA AVATAR</button></form>}

export function TypeFields({defaults}:{defaults?:{type?:string;seasonalStart?:string|null;seasonalEnd?:string|null;keepAfterUnlock?:boolean;unlockType?:string|null;unlockValue?:number|null}}){return <><label className="block"><span className="mb-1 block text-xs font-black uppercase text-zinc-500">Tipo</span><select name="type" defaultValue={defaults?.type??'base'} className="h-12 w-full rounded-xl bg-zinc-950 px-3"><option value="base">Base</option><option value="seasonal">Stagionale</option><option value="unlockable">Sbloccabile</option></select></label><div className="grid grid-cols-2 gap-2"><input name="seasonalStart" defaultValue={defaults?.seasonalStart??''} placeholder="Inizio MM-GG" className="h-12 rounded-xl bg-zinc-950 px-3"/><input name="seasonalEnd" defaultValue={defaults?.seasonalEnd??''} placeholder="Fine MM-GG" className="h-12 rounded-xl bg-zinc-950 px-3"/></div><div className="grid grid-cols-2 gap-2"><select name="unlockType" defaultValue={defaults?.unlockType??''} className="h-12 rounded-xl bg-zinc-950 px-3"><option value="">Requisito...</option><option value="season_wins">Stagioni vinte</option><option value="trending_count">Volte Trending</option><option value="completed_penalties">Penitenze completate</option><option value="spent_euros">€ pagati</option></select><input name="unlockValue" type="number" min="1" defaultValue={defaults?.unlockValue??''} placeholder="Quantità" className="h-12 rounded-xl bg-zinc-950 px-3"/></div><label className="flex items-center gap-3 rounded-xl bg-zinc-950 p-3 text-sm font-bold"><input name="keepAfterUnlock" type="checkbox" defaultChecked={defaults?.keepAfterUnlock??true}/> Resta disponibile dopo lo sblocco</label><p className="text-[11px] leading-5 text-zinc-600">Per gli avatar Stagionali usa MM-GG: ad esempio 10-01 → 11-02. Le date si ripetono ogni anno.</p></>}
